feat [ADO.NET]: impl DbParameter
ydb-platform/ydb-dotnet-sdk pull request #124
Opened 2024-06-06 17:21 UTC by KirillKurdyukov

2024-06-06 18:28 UTC, MaxShoshin requested changes

2024-06-06 18:28 UTC, MaxShoshin commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +    private YdbValue YdbValueFromObject()
метод выглядит странно. 
вроде бы он получает YdbValue из текущего класса.... но в процессе он меняет внутреннее состояние.

2024-06-06 18:28 UTC, MaxShoshin commented on src/Ydb.Sdk/src/Ado/YdbAdoException.cs
> +public class YdbAdoException : Exception
есть довольно строгие правила как нужно определять Exceptions (сериализуемые, с публичным пустым конструктором)

2024-06-06 18:28 UTC, MaxShoshin commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +    public YdbParameter(string parameterName)
кажется очень не хватает других разных конструкторов

2024-06-06 18:28 UTC, MaxShoshin commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +            _ => throw new YdbAdoException($"Error converting {Value?.GetType().ToString() ?? "null"} to YdbValue")
в случае null или DBNull.Value тут будет исключение

2024-06-06 18:28 UTC, MaxShoshin commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +                                  $"{typeof(T) + (IsNullable ? "?" : ", isNullable = false")}");
IsNullabel кажется это про тип параметра (Optional или нет в базе), с вопросиком наверное не стоит смешивать.

2024-06-06 18:28 UTC, MaxShoshin commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +        if (Value is T v)
не очень понимаю как поведут себя другие реализации если например засунем туда например long, а DbType от int32

2024-06-06 20:01 UTC, KirillKurdyukov commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +            _ => throw new YdbAdoException($"Error converting {Value?.GetType().ToString() ?? "null"} to YdbValue")
Да, так как Ydb строго типизированная база данных, здесь ничего мы не сможем сделать и угадать, что имел пользователь.

2024-06-06 20:02 UTC, KirillKurdyukov commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +        if (Value is T v)
Будет исключение, которое говорит, какой тип ожидался при таком DbType

2024-06-06 20:08 UTC, KirillKurdyukov commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +    public YdbParameter(string parameterName)
Кажется что излишне, ведь все фреймворки работают над интерфейсом, который именно через сеттеры.

2024-06-07 07:23 UTC, KirillKurdyukov commented on src/Ydb.Sdk/src/Ado/YdbParameter.cs
> +    private YdbValue YdbValueFromObject()
Он меняет внутреннее состояние, чтобы переиспользовать ранее написанный код

2024-06-07 08:53 UTC, alex268 approved these changes

2024-06-07 10:10 UTC, KirillKurdyukov commented
В очном формате пришли к следующему:

- enum для YdbType (аналог DbType) не требуется, так как можно явно засетить YdbValue
- cложные конструкции parameter не требуются, так как можно пользоваться конструкторами YdbValue
- исключение с публичным конструктором, (Exception уже сериализуем)
- Если object == null, и не знаем DbType => формируем исключение, так как Optional в Ydb строго типизируем
- DbType = Object, определяем тип по object != null 
- TypeConverter откладываем, так как явной потребности на данный момент нет. (возможна потеря данных на клиенте, здесь не рискуем, имплементируем хеппи path)

2024-06-07 10:37 UTC, merged